############################################################
# <bsn.cl fy=2013 v=none>
#
#        Copyright 2013, 2014 BigSwitch Networks, Inc.
#
#
#
# </bsn.cl>
############################################################
ARCH=amd64
PACKAGE_NAMES=initrd-amd64
include ../../../../make/debuild.mk



