#
# /etc/syslog.conf
#
#  Copyright (C) 2013 Curt Brune <curt@cumulusnetworks.com>
#
#  SPDX-License-Identifier:     GPL-2.0

#
# onie syslog configuration file
#

# Use facility local0 for onie.
local0.*                /var/log/onie.log

# Copy all logs to update.log for sharing with SONiC
*.*                     /mnt/onie-boot/onie/update/update.log

# Everything else to /var/log/messages (excluding local0 and update.log duplicates)
*.*;local0.none         /var/log/messages
