#!/bin/sh

# Overrides install.sh
check_machine_image()
{
    platform=$(/usr/bin/mb_detect -p)
    image_platform_machine=$(echo $image_machine | sed "s/bwde/${platform}/g")
    echo "ONIE: Platform Machine: $image_platform_machine"

    if [ "$onie_machine" != "$image_machine" ] && [ "$onie_machine" != "$image_platform_machine" ] ; then
        fail=yes
    fi
    if [ "$onie_machine_rev" != "$image_machine_rev" ] ; then
        fail=yes
    fi
    if [ "$onie_arch" != "$image_arch" ] ; then
        fail=yes
    fi
}

