#!/bin/sh

#  Copyright (C) 2014 Curt Brune <curt@cumulusnetworks.com>
#  Copyright (C) 2015 david_yang <david_yang@accton.com>
#
#  SPDX-License-Identifier:     GPL-2.0

# This file provides a GRUB menu entry for ONIE.
#
# Place this file in /etc/grub.d and grub-mkconfig will use this file
# when generating a grub configuration file.

ONIE_CMDLINE="quiet $GRUB_ONIE_CMDLINE_LINUX"
for mode in install rescue uninstall update embed ; do
    case "$mode" in
        install)
            boot_message="ONIE: OS Install Mode ..."
            ;;
        rescue)
            boot_message="ONIE: Rescue Mode ..."
            ;;
        uninstall)
            boot_message="ONIE: OS Uninstall Mode ..."
            ;;
        update)
            boot_message="ONIE: ONIE Update Mode ..."
            ;;
        embed)
            boot_message="ONIE: ONIE Embed Mode ..."
            ;;
        *)
            ;;
    esac
    (cat <<EOF
menuentry "\$onie_menu_$mode" {
        onie_entry_start
        echo    "$boot_message"
        linux   /onie/vmlinuz-\${onie_kernel_version}-onie $ONIE_CMDLINE boot_reason=$mode
        initrd  /onie/initrd.img-\${onie_kernel_version}-onie
        onie_entry_end
}
EOF
    )
done
