############################################################
# <bsn.cl fy=2013 v=none>
#
#        Copyright 2013, 2014 BigSwitch Networks, Inc.
#
#
#
# </bsn.cl>
############################################################
ifndef ARCH
$(error $$ARCH is not specified.)
endif

ifndef BUILD_DIR_BASE
$(error $$BUILD_DIR_BASE is not specified.)
endif

PACKAGE_NAMES=onlp onlp-dbg
include ../../../../../make/debuild.mk

