#!/bin/sh

#  Copyright (C) 2018 Curt Brune <curt@cumulusnetworks.com>
#
#  SPDX-License-Identifier:     GPL-2.0

ONIE_REPO="https://github.com/opencomputeproject/onie.git"
DEST_DIR="/home/build/src/onie"

mkdir -p $(dirname $DEST_DIR)
git clone "$ONIE_REPO" "$DEST_DIR"
