#!/bin/bash
############################################################
# <bsn.cl fy=2013 v=onl>
# 
#        Copyright 2013, 2014 Big Switch Networks, Inc.       
# 
# Licensed under the Eclipse Public License, Version 1.0 (the
# "License"); you may not use this file except in compliance
# with the License. You may obtain a copy of the License at
# 
#        http://www.eclipse.org/legal/epl-v10.html
# 
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
# either express or implied. See the License for the specific
# language governing permissions and limitations under the
# License.
# 
# </bsn.cl>
############################################################
#
# chws
#
############################################################
WS_ROOT=.
while [ ! -f "${WS_ROOT}/.pandora-ws" ]; do
    if [ "${WS_ROOT}" -ef / ]; then
	echo "Must run within a pandora workspace" 2>&1
	exit 1
    fi
    WS_ROOT="${WS_ROOT}/.."
done
export WS_ROOT=$(realpath "${WS_ROOT}")
export OPENSSL_ppccap=0
sudo update-binfmts --enable

if [ $# -lt 1 ]; then
    set -- bash
fi

isolate -c $(dirname "$0")/chws-child -o "${WS_ROOT}" "$@"
