#!/bin/sh
#Ensure that Lenovo NOS device tree partition is erased for complete cleanness
#Note Lenovo RFS and kernel NOR partitions are covered by mtd-open which is 
#handled in the uninstall-arch script
if [ -h /dev/mtd-device-tree ]; then
	printf "${log_pre}Erasing Lenovo DFT NOR flash region"
	flash_unlock /dev/mtd-device-tree > /dev/null 2>&1
	flash_erase /dev/mtd-device-tree 0 0
fi
