ifndef ONL
$(error $$ONL is undefined.)
endif

ONL_REQUIRED_SUBMODULES := bigcode infra common
ONL_REQUIRED_PACKAGES := onlp:amd64

ARCH := x86_64
TOOLCHAIN := x86_64-linux-gnu

include $(ONL)/make/component.mk
