#!/bin/sh

#  Copyright (C) 2014 Curt Brune <curt@cumulusnetworks.com>
#
#  SPDX-License-Identifier:     GPL-2.0

# x86_64 boot mode implemenations see /etc/init.d/discover.sh

# We want rescue mode booting to be a one time operation.  After the
# rescue mode we should return to the default state.  On this
# architecture no action is necessary.
rescue_revert_default_arch()
{
    return 0
}

# We want install mode booting to be sticky, e.g. if you boot into
# install mode you stay install mode until an installer runs
# successfully.  On this architecture no action is necessary.
install_remain_sticky_arch()
{
    return 0
}

# Local Variables:
# mode: shell-script
# eval: (sh-set-shell "/bin/sh" t nil)
# End:
