#!/bin/sh

# x86_64 boot mode implemenations see /etc/init.d/discover.sh

# We want rescue mode booting to be a one time operation.  After the
# rescue mode we should reboot into the previous state.
rescue_revert_default_arch()
{
    # Clear any ONIE boot mode
    onie-boot-default -q -o none
    onie-boot-update -q
    return 0
}

# We want install mode booting to be sticky, i.e. if you boot into
# install mode you stay install mode until an installer runs
# successfully.
install_remain_sticky_arch()
{
    onie-boot-default -q -o install
    onie-boot-update -q
    return 0
}

# Local Variables:
# mode: shell-script
# eval: (sh-set-shell "/bin/sh" t nil)
# End:
