#!/bin/bash

CONFIG="$1"
CONFIGOPTS="$2"

if [ -z "$CONFIG" -o ! -f "$CONFIG" ]; then
    echo "ERROR: $CONFIG not found!"
    echo "Usage: $0 /path/to/config-file /path/to/extra-config-options-file"
    exit 100
fi

# If the config options file is not present, do a successful exit
[ -r $CONFIGOPTS ] || exit 0

# Iterate through all the config options in $CONFIGOPTS and replace their
# existence in $CONFIG with corresponding lines from $CONFIGOPTS

while read bbopt; do
    optname=${bbopt%%=*}
    sed -i "/\b$optname\b/c\\$bbopt" $CONFIG
done <$CONFIGOPTS
