############################################################
# <bsn.cl fy=2013 v=none>
# 
#        Copyright 2013, 2014 BigSwitch Networks, Inc.        
# 
# 
# 
# </bsn.cl>
############################################################
ifndef ONL
$(error $$ONL is undefined.)
endif

# ONL_REQUIRED_SUBMODULES := 
ONL_REQUIRED_PACKAGES := vendor-config-onl:all

include $(ONL)/make/component.mk
