#!/bin/sh

# Lenovo Copyright, 2017
# Platform specific hardware init

init_cpld() 
{
    i2cset -y 0 0x5e 0x07 0x00
}

# Use this function to perform any initializations required by the
# architecture specific initialization.  This function executes before
# the architecture initializations.
init_platform_pre_arch() 
{
    init_cpld 2> /dev/null
}
