#!/bin/sh
############################################################
# <bsn.cl fy=2013 v=onl>
#
#        Copyright 2013, 2014 Big Switch Networks, Inc.
#        Copyright 2015 Quanta Computer Inc.
#
# Licensed under the Eclipse Public License, Version 1.0 (the
# "License"); you may not use this file except in compliance
# with the License. You may obtain a copy of the License at
#
#        http://www.eclipse.org/legal/epl-v10.html
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
# either express or implied. See the License for the specific
# language governing permissions and limitations under the
# License.
#
# </bsn.cl>
############################################################
#
# Platform: Quanta LY6
#
############################################################

cur_dir=$(dirname $0)
if [ -x $cur_dir/functions ]; then
	. $cur_dir/functions
else
	echo "$cur_dir/functions not found"
	exit 1
fi

usage() {
    echo "Two parameters <devices {fan1|fan2|fan3}> and <led color {red|off}> required"
}

case $1 in
    1|fan1)
        offset=0
        ;;

    2|fan2)
        offset=1
        ;;

    3|fan3)
        offset=2
        ;;

    *)
        usage
        exit 1
        ;;
esac

case $2 in
    1|red)
        p=1
        ;;
    0|off)
        p=0
        ;;

    *)
        usage
        exit 1
        ;;
esac

pca9555_24=$(gpio_find 24)
pca9555_24p14=$(($pca9555_24 + $pca953x_p14))
gpio=$(($pca9555_24p14 + $offset))

gpio_set $gpio $p

exit 0
