#!/bin/sh
############################################################
# <bsn.cl fy=2013 v=onl>
#
#        Copyright 2013, 2014 Big Switch Networks, Inc.
#        Copyright 2015 Quanta Computer Inc.
#
# Licensed under the Eclipse Public License, Version 1.0 (the
# "License"); you may not use this file except in compliance
# with the License. You may obtain a copy of the License at
#
#        http://www.eclipse.org/legal/epl-v10.html
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
# either express or implied. See the License for the specific
# language governing permissions and limitations under the
# License.
#
# </bsn.cl>
############################################################
#
# Platform: Quanta LY6
#
############################################################

echo $$ > /var/run/frontled.pid

wait=10

frontled=$(dirname $0)/frontled
fanstatus=$(dirname $0)/fanstatus

while true
do
    psu1_status=$(sensors *-i2c-*-58 | grep Vin | sed -r 's/.*\+([0-9]+)\..*/\1/g')
    psu2_status=$(sensors *-i2c-*-59 | grep Vin | sed -r 's/.*\+([0-9]+)\..*/\1/g')
    fan_status=$(fanstatus | grep warn)

    if [ ! "$psu1_status" = "0" ]; then
        $frontled psu1 green
    else
        $frontled psu1 red
    fi

    if [ ! "$psu2_status" = "0" ]; then
        $frontled psu2 green
    else
        $frontled psu2 red
    fi

    if [ "$fan_status" = "" ]; then
        $frontled fan green
    else
        $frontled fan red
    fi

    sleep $wait
done

exit 0

