#!/bin/sh

. ./platform-discover

# Overrides function in install.sh
check_machine_image()
{
    bigstone_g_card_detect
    if [ -n "${platform}" ] ; then
        image_platform_machine=$(echo $image_build_machine | sed "s/cel_bigstone_g/cel_bigstone_g_${platform}/g")
    fi
    echo "ONIE: Platform Machine: $image_platform_machine"

    if [ "$onie_build_machine" != "$image_build_machine" ] &&
       [ "$onie_build_machine" != "$image_platform_machine" ] ; then
        fail=yes
    fi
    if [ "$onie_machine_rev" != "$image_machine_rev" ] ; then
        fail=yes
    fi
    if [ "$onie_arch" != "$image_arch" ] ; then
        fail=yes
    fi
}
