#!/bin/bash
############################################################
# <bsn.cl fy=2013 v=onl>
#
#	Copyright 2013, 2014 Big Switch Networks, Inc.
#       Copyright 2015 Quanta Computer Inc.
#
# Licensed under the Eclipse Public License, Version 1.0 (the
# "License"); you may not use this file except in compliance
# with the License. You may obtain a copy of the License at
#
#	http://www.eclipse.org/legal/epl-v10.html
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
# either express or implied. See the License for the specific
# language governing permissions and limitations under the
# License.
#
# </bsn.cl>
############################################################
#
# Platform: Quanta LY8
#
############################################################

echo $$ > /var/run/fanled.pid

wait=10

fanled=$(dirname $0)/fanled
fans=(1 2 3 5 6 7)
fanleds=(1 2 3 1 2 3)
hwmon=quanta_ly8_hwmon
min_rpm=3000

while true
do
	for i in `seq 0 $((${#fans[@]}-1))`; do
		status=$(fanstatus ${fans[$i]} -n)
		if [ "$status" == "ok" ]; then
			fanled fan${fanleds[$i]} off
		else
			fanled fan${fanleds[$i]} red
		fi
	done

    sleep $wait
done

exit 0

