#!/bin/sh

DIR=/persist/rootfs

if [ ! -d $DIR ] ; then
        echo "FAILURE: directory $DIR does not exists" >&2
        exit 1
fi

if [ $# = 0 ] ; then
    echo "Usage: $0 /path/to/file1 [/path/to/file2 [...]]" >&2
    exit 2
fi



for f in $@; do 
    F=$(readlink -f $f)
    D=`dirname $F`
    echo Saving $f to $DIR/$F
    if [ ! -d $DIR/$D ] ; then
        echo Making dir $DIR/$D
        mkdir -p $DIR/$D
    fi
    ln -f $f $DIR/$F
done
