#!/bin/sh
############################################################
# <bsn.cl fy=2013 v=onl>
# 
#        Copyright 2013, 2014 BigSwitch Networks, Inc.        
# 
# Licensed under the Eclipse Public License, Version 1.0 (the
# "License"); you may not use this file except in compliance
# with the License. You may obtain a copy of the License at
# 
#        http://www.eclipse.org/legal/epl-v10.html
# 
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
# either express or implied. See the License for the specific
# language governing permissions and limitations under the
# License.
# 
# </bsn.cl>
############################################################
#
# waitforsysdev
#
# Wait for a sys device to appear on $1, time out after 10 seconds
#
############################################################
i=10
while [ $i -gt 0 ]; do
    find /sys/devices | grep -q $1 && break
    sleep 1
    let i--
done
[ $i -gt 0 ] || { echo "Timed out waiting for $1"; exit 1; }
