#!/bin/sh
############################################################
# <bsn.cl fy=2013 v=none>
#
#        Copyright 2013, 2014 BigSwitch Networks, Inc.
#
#
#
# </bsn.cl>
############################################################
#
# waitforsysdev
#
# Wait for a sys device to appear (as $1), time out after
# a specified interval (10s by default)
#
############################################################

dev=$1; shift
if test $# -gt 0; then
  timeout=$1; shift
else
  timeout=10
fi
i=$timeout
while test $i -gt 0; do
  find /sys/devices | grep $dev 1>/dev/null && break
  sleep 1
  i=$(( $i - 1 ))
done
[ $i -gt 0 ] || { echo "Timed out waiting for $dev"; exit 1; }
