#!/bin/bash

rootfs=$1

[ -n "$rootfs" ]  || (echo "Error: need to specify a rootfs" && exit -1)
[ -d "$rootfs" ]  || (echo "Error: rootfs \"${rootfs}\" does not exist" && exit -1)
[ "$rootfs" != "/" ] || (echo "Error: will not modify \"${rootfs}\"" && exit -1)

ROOTFS="$(realpath ${rootfs})" && echo "Installing in ${ROOTFS}"

################################################################################
#
# Check to see if we have sudo or root priviledge
#

[ ${UID} == 0 ] || (echo "Error: must be root to run ${0}" && exit -1)

TAR_OPTS="--exclude=*~ --exclude-backups --owner=root --group=root"
echo "Copying default rootfs into target rootfs"
tar --directory=default $TAR_OPTS  -cf - . | ( cd $ROOTFS; tar -xpf - )
