#!/bin/sh
#Ensure that Lenovo NOS device tree partition along with RFS, kernel, 
#rsvd0/1 and MMC are erased for complete cleanness

if [ -h /dev/mtd-device-tree ]; then
	echo "Erasing Lenovo DFT NOR flash region"
	flash_unlock /dev/mtd-device-tree > /dev/null 2>&1
	flash_erase /dev/mtd-device-tree 0 0
fi

if [ -h /dev/mtd-linux-kernel ]; then
	echo "Erasing Lenovo Kernel NOR flash region"
	flash_unlock /dev/mtd-linux-kernel > /dev/null 2>&1
	flash_erase /dev/mtd-linux-kernel 0 0
fi

if [ -h /dev/mtd-root ]; then
	echo "Erasing Lenovo RFS NOR flash region"
	flash_unlock /dev/mtd-root > /dev/null 2>&1
	flash_erase /dev/mtd-root 0 0
fi

if [ -h /dev/mtd-rsvd0 ]; then
	echo "Erasing Lenovo rsvd0 NOR flash region"
	flash_unlock /dev/mtd-rsvd0 > /dev/null 2>&1
	flash_erase /dev/mtd-rsvd0 0 0
fi

if [ -h /dev/mtd-rsvd1 ]; then
	echo "Erasing Lenovo rsvd1 NOR flash region"
	flash_unlock /dev/mtd-rsvd1 > /dev/null 2>&1
	flash_erase /dev/mtd-rsvd1 0 0
fi

if [ -b /dev/mmcblk0 ]; then
	echo "Erasing Lenovo MMC storage region"
#	umount /dev/mmcblk0p4 > /dev/null 2>&1
#	umount /dev/mmcblk0p3 > /dev/null 2>&1
#	umount /dev/mmcblk0p2 > /dev/null 2>&1
#	umount /dev/mmcblk0p1 > /dev/null 2>&1
#	mkfs.ext3 -b 4096 /dev/mmcblk0p1 > /dev/null 2>&1
#	mkfs.ext3 -b 4096 /dev/mmcblk0p2 > /dev/null 2>&1
#	mkfs.ext3 -b 4096 /dev/mmcblk0p3 > /dev/null 2>&1
#	mkfs.ext3 -b 4096 /dev/mmcblk0p4 > /dev/null 2>&1
	dd if=/dev/zero of=/dev/mmcblk0 bs=512 count=1 > /dev/null 2>&1
fi
