#!/bin/sh

# Overrides install.sh

update_syseeprom()
{
    # Set platform name and ONIE version to sys_eeprom.
    if [ -x /usr/bin/onie-syseeprom ] ; then
        local syseeprom_log=$(mktemp)
        onie-syseeprom \
            -s 0x29="2020.02-rc1" \
            > $syseeprom_log 2>&1 || {
            echo "ERROR: Problems accessing sys_eeprom"
            cat $syseeprom_log && rm -f $syseeprom_log
            exit 1
        }
        [ "$verbose" = "yes" ] && cat $syseeprom_log
        rm -f $syseeprom_log
    fi
}

