#!/bin/sh

#  Copyright (C) 2014 Curt Brune <curt@cumulusnetworks.com>
#  Copyright (C) 2015-2016 david_yang <david_yang@accton.com>
#
#  SPDX-License-Identifier:     GPL-2.0

this_script=$(basename $(realpath $0))
lib_dir="$(dirname $(realpath $0))/../lib/onie"

args="o:flhvq"

usage()
{
    echo "usage: $this_script [-o <onie_mode>] [-flhvq]"
    cat <<EOF
Get or set the default GRUB boot entry.  The default is to show
the current default entry.

Some boot entries are "one time", like "rescue" mode.  After they run
once, these boot modes clear and the default becomes active for
subsequent boots.

To make a boot option persistent, set it as the "fallback" using the
-f option.

COMMAND LINE OPTIONS

	-o
		Set the default GRUB boot entry to a particular "ONIE
		mode".  Available ONIE modes are:

		install   -- ONIE OS installer mode
		rescue    -- ONIE rescue mode
		uninstall -- ONIE OS uninstall mode
		update    -- ONIE self update mode
		embed     -- ONIE self update mode and embed ONIE
		diag      -- Hardware Vendor's Diagnostic
		none      -- Use system default boot mode

                Some platforms may offer additional modes.  Check with
                your hardware vendor.

                The 'none' mode will use the first ONIE boot menu entry.

                When combined with the -f option, set the fallback
                entry instead of the default entry.

        -f
                Set the fallback GRUB boot entry specified by the -o
                option.  Only valid when used in conjunction with the
                -o option.

	-l
		List the current default entry.  This is the default.

		When combined with the -f option, the fallback entry
		is displayed instead.

	-h
		Help.  Print this message.

	-q
		Quiet.  No printing, except for errors.

	-v
		Be verbose.  Print what is happening.
EOF
}

onie_mode=
fallback=
list=
quiet=no
verbose=no
cmd_verbose=

while getopts "$args" a ; do
    case $a in
        h)
            usage
            exit 0
            ;;
        v)
            verbose=yes
            cmd_verbose=-v
            ;;
        l)
            list=yes
            ;;
        o)
            onie_mode="$OPTARG"
            ;;
        f)
            fallback=yes
            ;;
        q)
            quiet=yes
            ;;
        *)
            echo "Unknown argument: $a"
            usage
            exit 1
    esac
done

[ "$verbose" = "yes" ] && quiet=no

[ -r "$lib_dir/onie-blkdev-common" ] || {
    echo "ERROR: Unable to find onie-blkdev-common"
    exit 1
}
. $lib_dir/onie-blkdev-common

if [ "$fallback" = "yes" ] ; then
    label="Fallback"
    grub_env=onie_fallback
else
    label="Default"
    grub_env=onie_mode
fi


if [ -n "$onie_mode" ] ; then
    case "$onie_mode" in
        install|uninstall|rescue|update|embed|diag)
            [ "$verbose" = "yes" ] && echo "Setting ONIE $label mode to: $onie_mode"
            onie_setenv $grub_env "$onie_mode"
            ;;
        none)
            [ "$verbose" = "yes" ] && echo "Clearing the ONIE $label mode"
            onie_setenv $grub_env
            ;;
        *)
            echo "ERROR: Unknown ONIE mode: $onie_mode"
            exit 1
    esac
fi

if [ -z "$onie_mode" ] || [ "$list" = "yes" ] ; then
    # Read ONIE mode from grubenv
    mode="$(onie_getenv $grub_env)"
    if [ -n "$mode" ] ; then
        default="$mode"
    else
        default="none"
    fi
    echo "$label ONIE mode: $default"
fi

exit 0
