############################################################
# <bsn.cl fy=2013 v=none>
#
#        Copyright 2013, 2014 BigSwitch Networks, Inc.
#
#
#
# </bsn.cl>
############################################################
ARCH=amd64
PACKAGE_NAMES=kernel-3.2-deb7-x86_64-all kernel-3.2-deb7-x86_64-all-mbuild
include ../../../../../make/debuild.mk



