# -*- Makefile -*-
############################################################
#
# @make-cl-start
# @make-cl-end
#
############################################################
ifndef ONL
$(error $$ONL is not set)
endif

include $(ONL)/make/config.mk

all:
	@echo Run 'make deb'

.PHONY: deb
deb:
	$(MAKE) -C deb
