############################################################
# <bsn.cl fy=2013 v=none>
#
#        Copyright 2013, 2014 BigSwitch Networks, Inc.
#
#
#
# </bsn.cl>
############################################################
ARCH=all
PACKAGE_NAMES=platform-config-x86-64-dell-s4000-c2338-r0
include ../../../../../make/debuild.mk
