# -*- Makefile -*-
############################################################
ifndef ONL
$(error $$ONL is not set)
endif

include $(ONL)/make/config.mk

all:
	@echo Nothing to be done.

.PHONY: deb
deb:
	$(MAKE) -C deb
