############################################################
# <bsn.cl fy=2013 v=none>
#
#        Copyright 2013, 2014 BigSwitch Networks, Inc.
#        Copyright 2015 Quanta Computer Inc.
#
#
#
# </bsn.cl>
############################################################
ARCH=all
PACKAGE_NAMES=platform-config-x86-64-quanta-ly8-rangeley-r0
include ../../../../../make/debuild.mk
