#!/bin/sh

#  Copyright (C) 2013 Curt Brune <curt@cumulusnetworks.com>
#
#  SPDX-License-Identifier:     GPL-2.0

# This is only called by early boot scripts when something goes really
# wrong.

reboot_after=$1

echo "Spawning debug shell so you can have a look ..."
if [ "$reboot_after" = "1" ] ; then
    echo "Type ctrl-d or \"exit\" to reboot"
else
    echo "Type ctrl-d or \"exit\" to continue boot process"
fi
setsid cttyhack /bin/sh

if [ "$reboot_after" = "1" ] ; then
    reboot
fi
