# -*- Makefile -*-
############################################################
# <bsn.cl fy=2013 v=none>
#
#        Copyright 2013, 2014 BigSwitch Networks, Inc.
#        Copyright 2015 Quanta Computer Inc.
#
#
#
# </bsn.cl>
############################################################
############################################################
ifndef ONL
$(error $$ONL is not set)
endif

include $(ONL)/make/config.mk

all:
	@echo Run 'make deb'

.PHONY: deb
deb:
	$(MAKE) -C deb
