ifndef ONL
$(error $$ONL is undefined.)
endif

ONL_REQUIRED_SUBMODULES := bigcode infra common
ONL_REQUIRED_PACKAGES := onlp:powerpc

ARCH := powerpc
TOOLCHAIN := powerpc-linux-gnu

include $(ONL)/make/component.mk
