#!/bin/sh
### BEGIN INIT INFO
# Provides:          loadstartupconfig
# Required-Start:    $remote_fs
# Required-Stop:
# Should-Start:      faultd
# Should-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Load startup-config
### END INIT INFO


PATH=/sbin:/usr/sbin:/bin:/usr/bin

. /lib/init/vars.sh
. /lib/lsb/init-functions

case "$1" in
    start)
        if [ -e /etc/onl_startup-config ]; then
            log_action_begin_msg "Loading startup-config from SWI"
	    config=/etc/onl_startup-config
        elif [ -e /mnt/flash/startup-config ]; then
            log_action_begin_msg "Loading flash:startup-config"
	    config=/mnt/flash/startup-config
	else
	    log_action_begin_msg "Loading empty startup-config"
	    config=/dev/null
	fi
        /usr/bin/pcli --init --mode=config <${config} >/var/log/loadstartupconfig 2>&1
        log_action_end_msg $?
        ;;
    restart|reload|force-reload)
        echo "Error: argument '$1' not supported" >&2
        exit 3
        ;;
    stop)
        ;;
    *)
        echo "Usage: $0 start|stop" >&2
        exit 3
        ;;
esac
