#!/bin/bash

### BEGIN INIT INFO
# Provides:        sensors-baseconf
# Required-Start:  initdev
# Required-Stop:
# Default-Start:   S
# Default-Stop:
# Short-Description: Set up platform-specific sensors config
### END INIT INFO

. /lib/lsb/init-functions

plat=$(cat /etc/onl_platform 2>/dev/null)

[ "${plat}" ] || exit 0

log_action_begin_msg "Setting up sensors configuration"

platform_sensors=/lib/platform-config/${plat}/etc/sensors3.conf
if [ -f ${platform_sensors} ]; then
    ln -snf ${platform_sensors} /etc/sensors3.conf
fi

platform_fancontrol=/lib/platform-config/${plat}/etc/fancontrol
if [ -f ${platform_fancontrol} ]; then
    ln -snf  ${platform_fancontrol} /etc/fancontrol
fi

log_action_end_msg 0
