############################################################
# <bsn.cl fy=2013 v=none>
#
#        Copyright 2013, 2014 BigSwitch Networks, Inc.
#        Copyright 2015 Quanta Computer Inc.
#
#
#
# </bsn.cl>
############################################################
ARCH := amd64
ONL_V_at :=
PACKAGE_NAMES=onlp-x86-64-quanta-ly6-rangeley-r0
include ../../../../../make/debuild.mk
