#!/bin/sh

# Overrides install.sh
check_machine_image()
{
    if [ "$onie_build_machine" != "$image_build_machine" ] ; then
        onie_machine_series=$(echo $onie_build_machine | cut -d '_' -f 2 | cut -c1-3)
        image_machine_series=$(echo $image_build_machine  | cut -d '_' -f 2 | cut -c1-3)
        if [ "$onie_machine_series" != "$image_machine_series" ] ; then
            fail=yes
        fi
    fi  
    if [ "$onie_machine_rev" != "$image_machine_rev" ] ; then
        fail=yes
    fi  
    if [ "$onie_arch" != "$image_arch" ] ; then
        fail=yes
    fi  
}

