#!/bin/sh

# Mount the ONIE partitions

. /lib/onie/functions

this_script=$(basename $(realpath $0))
lib_dir="$(dirname $(realpath $0))/../lib/onie"

[ -r "$lib_dir/onie-blkdev-common" ] || {
    echo "ERROR: Unable to find onie-blkdev-common"
    exit 1
}
. $lib_dir/onie-blkdev-common

args="wuvh"

usage()
{
    echo "usage: $this_script [-${args}]"
    cat <<EOF
Mount and un-mount ONIE partitions.

Only one of -w or -u can be specified.

COMMAND LINE OPTIONS

	The default is to mount the ONIE-BOOT partition read-only and
	the ONIE-CONFIG partition read-write.

	-h
		Help.  Print this message.

	-v
		Be verbose.  Print what is happening.

	-w
		Mount the ONIE-BOOT partition read-write.

		WARNING:  Do not use this option unless you really know
		what you are doing.  Only advisable when updating ONIE.

		Cannot be used with the -u option.

	-u
		Un-mount the ONIE partitions.  Cannot be used
		with the -w option.
EOF
}

rw=no
umount=no
verbose=no

while getopts "$args" a ; do
    case $a in
        h)
            usage
            exit 0
            ;;
        w)
            rw=yes
            ;;
        u)
            umount=yes
            ;;
        v)
            verbose=yes
            ;;
        *)
            echo "Unknown argument: $a"
            usage
            exit 1
    esac
done

if [ "$rw" = "yes" ] && [ "$umount" = "yes" ] ; then
    echo "ERROR: Only one of the -w or -u options can be specified."
    usage
    exit 1
fi

mount_parts()
{
    boot_options="defaults"
    if [ "$rw" = "yes" ] ; then
        boot_options="${boot_options},rw"
        text="read-write"
    else
        boot_options="${boot_options},ro"
        text="read-only"
    fi

    [ "$verbose" = "yes" ] && echo "Mounting ONIE-BOOT $text on $onie_boot_mnt ..."
    mkdir -p $onie_boot_mnt
    mount -o "$boot_options" -t $onie_boot_fs_type "LABEL=$onie_boot_label" $onie_boot_mnt || {
        echo "ERROR: Problems mounting $onie_boot_label on $onie_boot_mnt"
        exit 1
    }

    [ "$verbose" = "yes" ] && echo "Mounting ONIE-CONFIG read-write on $onie_config_mnt ..."
    mkdir -p $onie_config_mnt
    mount -o defaults,rw -t $onie_config_fs_type "LABEL=$onie_config_label" $onie_config_mnt || {
        echo "ERROR: Problems mounting $onie_config_label on $onie_config_mnt"
        exit 1
    }
}

umount_parts()
{
    [ "$verbose" = "yes" ] && echo "Un-mounting ONIE-BOOT from $onie_boot_mnt ..."
    umount $onie_boot_mnt || {
        echo "ERROR: Problems un-mounting ONIE-BOOT from $onie_boot_mnt"
        exit 1
    }

    [ "$verbose" = "yes" ] && echo "Un-mounting ONIE-CONFIG from $onie_config_mnt ..."
    umount $onie_config_mnt || {
        echo "ERROR: Problems un-mounting ONIE-CONFIG from $onie_config_mnt"
        exit 1
    }
}

if [ "$umount" = "yes" ] ; then
    umount_parts
else
    mount_parts
fi
