#!/bin/sh

this_script=$(basename $(realpath $0))
lib_dir="$(dirname $(realpath $0))/../lib/onie"

args="n:c:hvq"

usage()
{
    echo "usage: $this_script -n <entry_name> -c <entry_config_file> [-hvq]"
    cat <<EOF
Add GRUB configuration file to ONIE GRUB configuration.

The -n and -c arguments are required.

COMMAND LINE OPTIONS

	-n
		GRUB configuration fragment name.  This argument is required.
                Example:

                30_NOS_xx   <-- 30_xxx for NOS use

	-c
		File name containing the GRUB fragment to add.  This
		argument is required.

                The contents of this file are copied into the final
		ONIE GRUB configuration file.

	-h
		Help.  Print this message.

	-q
		Quiet.  No printing, except for errors.

	-v
		Be verbose.  Print what is happening.
EOF
}

entry_name=
entry_config_file=
quiet=no
verbose=no
cmd_verbose=

while getopts "$args" a ; do
    case $a in
        h)
            usage
            exit 0
            ;;
        v)
            verbose=yes
            cmd_verbose=-v
            ;;
        n)
            entry_name="$OPTARG"
            ;;
        c)
            entry_config_file="$OPTARG"
            ;;
        q)
            quiet=yes
            ;;
        *)
            echo "Unknown argument: $a"
            usage
            exit 1
    esac
done

[ "$verbose" = "yes" ] && quiet=no

[ -n "$entry_name" ] || {
    echo "ERROR: configuration entry name not specified"
    usage
    exit 1
}

[ -n "$entry_config_file" ] || {
    echo "ERROR: configuration fragment file not specified"
    usage
    exit 1
}

[ -r "$entry_config_file" ] || {
    echo "ERROR: Unable to read configuration fragment file: $entry_config_file"
    usage
    exit 1
}

[ -r "$lib_dir/onie-blkdev-common" ] || {
    echo "ERROR: Unable to find onie-blkdev-common"
    exit 1
}
. $lib_dir/onie-blkdev-common

[ "$verbose" = "yes" ] && echo "Mounting ONIE partitions ..."
onie_mount_partitions || {
    echo "ERROR: Unable to mount ONIE partitions"
    exit 1
}

[ "$verbose" = "yes" ] && echo "copy $entry_config_file => $onie_config_mnt/grub.d/$entry_name"
/bin/cp "$entry_config_file" "$onie_config_mnt/grub.d/$entry_name" || {
    echo "ERROR: Problems copying $entry_config_file to $onie_config_mnt/grub.d/$entry_name"
    exit 1
}

[ "$verbose" = "yes" ] && echo "Un-mounting ONIE partitions ..."
onie_umount_partitions

[ "$quiet" = "no" ] && echo "Success: Run \`onie-boot-update' to make changes take effect."
exit 0
