#!/bin/sh

# Overrides install.sh

## Default implementation for updating u-boot env
update_uboot_env()
{
    echo ">>> update_tomcat_uboot_env <<<"
    (cat <<EOF
onie_boot_reason
onie_build_date $image_build_date
EOF
    ) | fw_setenv -f -s -
}

install_image()
{
    echo ">>> install_image <<<"
    # install kernel
    install_onie_kernel

    # install u-boot
    #install_onie_uboot

    # update u-boot env
    update_tomcat_uboot_env
    #update_uboot_env

    # update sys_eeprom
    update_syseeprom

}
