#!/bin/sh

# Overrides install.sh

## Default implementation for updating u-boot env
update_uboot_env()
{
    echo ">>> update_uboot_env <<<"
    (cat <<EOF
onie_boot_reason
onie_version $image_version
onie_build_date $image_build_date
EOF
    ) | fw_setenv -f -s -
}

install_image()
{
    # install kernel
    install_onie_kernel

    # install u-boot
    # G3748 U-boot is independence.
    #install_onie_uboot

    # update u-boot env
    update_uboot_env

    # update sys_eeprom
    update_syseeprom

}
