# -*- coding: utf-8 -*-
#
#  Copyright (C) 2013 Curt Brune <curt@cumulusnetworks.com>
#
#  SPDX-License-Identifier:     GPL-2.0
#
# This file is execfile()d with the current directory set to its containing dir.
#
# Note that not all possible configuration values are present in this
# autogenerated file.
#
# All configuration values have a default; values that are commented out
# serve to show the default.

import sys, os
import guzzle_sphinx_theme

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#sys.path.insert(0, os.path.abspath('.'))

# -- General configuration -----------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
#needs_sphinx = '1.0'

# Add any Sphinx extension module names here, as strings. They can be extensions
# coming with Sphinx (named 'sphinx.ext.*') or your custom ones.
extensions = [
    'sphinx.ext.autodoc',
    'rst2pdf.pdfbuilder',
    'sphinx.ext.todo',
    ]

todo_include_todos=True

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The suffix of source filenames.
source_suffix = '.rst'

# The encoding of source files.
#source_encoding = 'utf-8-sig'

# The master toctree document.
master_doc = 'index'

# General information about the project.
project = u'Open Network Install Environment'
copyright = u'2013-2017, <a href="https://cumulusnetworks.com/">Cumulus Networks, Inc.</a>  All Rights Reserved'

# The version info for the project you're documenting, acts as replacement for
# |version| and |release|, also used in various other places throughout the
# built documents.
#
# The short X.Y version.
# version = '1.0'
# The full version, including alpha/beta/rc tags.
# release = '2013-05-28'

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#language = None

# There are two options for replacing |today|: either, you set today to some
# non-false value, then it is used:
#today = ''
# Else, today_fmt is used as the format for a strftime call.
#today_fmt = '%B %d, %Y'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
exclude_patterns = ['_build']

# The reST default role (used for this markup: `text`) to use for all documents.
#default_role = None

# If true, '()' will be appended to :func: etc. cross-reference text.
#add_function_parentheses = True

# If true, the current module name will be prepended to all description
# unit titles (such as .. function::).
#add_module_names = True

# If true, sectionauthor and moduleauthor directives will be shown in the
# output. They are ignored by default.
#show_authors = False

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = 'sphinx'

# A list of ignored prefixes for module index sorting.
#modindex_common_prefix = []


# -- Options for HTML output ---------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.

html_translator_class = 'guzzle_sphinx_theme.HTMLTranslator'
html_theme_path = guzzle_sphinx_theme.html_theme_path()
html_theme = 'guzzle_sphinx_theme'

# Register the theme as an extension to generate a sitemap.xml
extensions.append("guzzle_sphinx_theme")

# Guzzle theme options (see theme.conf for more information)
html_theme_options = {
    # Set the name of the project to appear in the sidebar
    "project_nav_name": "ONIE",
    "base_url": "",
    "homepage": "index",
    "projectlink": "https://github.com/opencomputeproject/onie",
}

# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.
#html_theme_options = {}

# Add any paths that contain custom themes here, relative to this directory.
#html_theme_path = []

# The name for this set of Sphinx documents.  If None, it defaults to
# "<project> v<release> documentation".
#html_title = None

# A shorter title for the navigation bar.  Default is the same as html_title.
#html_short_title = None

# The name of an image file (relative to this directory) to place at the top
# of the sidebar.
html_logo = 'images/ONIE-logo-green-160x60.png'

# The name of an image file (within the static path) to use as favicon of the
# docs.  This file should be a Windows icon file (.ico) being 16x16 or 32x32
# pixels large.
html_favicon = None

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']

# If not '', a 'Last updated on:' timestamp is inserted at every page bottom,
# using the given strftime format.
#html_last_updated_fmt = '%b %d, %Y'

# If true, SmartyPants will be used to convert quotes and dashes to
# typographically correct entities.
#html_use_smartypants = True

# Custom sidebar templates, maps document names to template names.
html_sidebars = {
    '**': ['logo-text.html',
           'globaltoc.html',
           'localtoc.html',
           'searchbox.html']
}

# Additional templates that should be rendered to pages, maps page names to
# template names.
#html_additional_pages = {}

# If false, no module index is generated.
html_domain_indices = False

# If false, no index is generated.
#html_use_index = True

# If true, the index is split into individual pages for each letter.
#html_split_index = False

# If true, links to the reST sources are added to the pages.
html_show_sourcelink = False

# If true, "Created using Sphinx" is shown in the HTML footer. Default is True.
html_show_sphinx = False

# If true, "(C) Copyright ..." is shown in the HTML footer. Default is True.
html_show_copyright = True

# If true, an OpenSearch description file will be output, and all pages will
# contain a <link> tag referring to it.  The value of this option must be the
# base URL from which the finished HTML is served.
#html_use_opensearch = ''

# This is the file name suffix for HTML files (e.g. ".xhtml").
#html_file_suffix = None

# Output file base name for HTML help builder.
# htmlhelp_basename = 'OpenNetworkInstallEnvironmentDocs'

# -- Options for PDF output --------------------------------------------------

# Grouping the document tree into PDF files. List of tuples
# (source start file, target name, title, author, options).
#
# If there is more than one author, separate them with \\.
# For example: r'Guido van Rossum\\Fred L. Drake, Jr., editor'
#
# The options element is a dictionary that lets you override
# this config per-document.
# For example,
# ('index', u'MyProject', u'My Project', u'Author Name',
#  dict(pdf_compressed = True))
# would mean that specific document would be compressed
# regardless of the global pdf_compressed setting.

pdf_documents = [
    ('index', u'ONIE', u'Open Network Install Environment', u'Author Name'),
]

# A comma-separated list of custom stylesheets. Example:
pdf_stylesheets = ['sphinx','kerning','a4']

# A list of folders to search for stylesheets. Example:
pdf_style_path = ['.', '_styles']

# Create a compressed PDF
# Use True/False or 1/0
# Example: compressed=True
#pdf_compressed = False

# A colon-separated list of folders to search for fonts. Example:
pdf_font_path = ['/opt/X11/share/fonts/TTF/']

# Language to be used for hyphenation support
#pdf_language = "en_US"

# Mode for literal blocks wider than the frame. Can be
# overflow, shrink or truncate
#pdf_fit_mode = "shrink"

# Section level that forces a break page.
# For example: 1 means top-level sections start in a new page
# 0 means disabled
pdf_break_level = 1

# When a section starts in a new page, force it to be 'even', 'odd',
# or just use 'any'
#pdf_breakside = 'any'

# Insert footnotes where they are defined instead of
# at the end.
#pdf_inline_footnotes = True

# verbosity level. 0 1 or 2
#pdf_verbosity = 0

# If false, no index is generated.
pdf_use_index = False

# If false, no modindex is generated.
#pdf_use_modindex = True

# If false, no coverpage is generated.
pdf_use_coverpage = False

# Name of the cover page template to use
#pdf_cover_template = 'sphinxcover.tmpl'

# Documents to append as an appendix to all manuals.
#pdf_appendices = []

# Enable experimental feature to split table cells. Use it
# if you get "DelayedTable too big" errors
#pdf_splittables = False

# Set the default DPI for images
#pdf_default_dpi = 72

# Enable rst2pdf extension modules (default is only vectorpdf)
# you need vectorpdf if you want to use sphinx's graphviz support
pdf_extensions = ['vectorpdf']

# Page template name for "regular" pages
#pdf_page_template = 'cutePage'

# Show Table Of Contents at the beginning?
#pdf_use_toc = True

# How many levels deep should the table of contents be?
pdf_toc_depth = 9999

# Add section number to section references
pdf_use_numbered_links = False

# Background images fitting mode
pdf_fit_background_mode = 'scale'

# --- Options for Latex Output ---

# latex_documents
#This value determines how to group the document tree into LaTeX
#source files. It must be a list of tuples (startdocname, targetname,
#title, author, documentclass, toctree_only), where the items are:
#
#  startdocname: document name that is the “root” of the LaTeX file. All
#  documents referenced by it in TOC trees will be included in the LaTeX
#  file too. (If you want only one LaTeX file, use your master_doc
#  here.)
#
#  targetname: file name of the LaTeX file in the output directory.
#
#  title: LaTeX document title. Can be empty to use the title of the
#  startdoc. This is inserted as LaTeX markup, so special characters
#  like a backslash or ampersand must be represented by the proper LaTeX
#  commands if they are to be inserted literally.
#
#  author: Author for the LaTeX document. The same LaTeX markup caveat
#  as for title applies. Use \and to separate multiple authors, as in:
#  'John \and Sarah'.
#
#  documentclass: Normally, one of 'manual' or 'howto' (provided by
#  Sphinx). Other document classes can be given, but they must include
#  the “sphinx” package in order to define Sphinx’ custom LaTeX
#  commands. “howto” documents will not get appendices. Also, howtos
#  will have a simpler title page.
#
#  toctree_only: Must be True or False. If True, the startdoc document
#  itself is not included in the output, only the documents referenced
#  by it via TOC trees. With this option, you can put extra stuff in the
#  master document that shows up in the HTML, but not the LaTeX output.
#
#New in version 0.3: The 6th item toctree_only. Tuples with 5 items are still accepted.

latex_documents = [
    ('index', u'Open_Network_Install_Environment.tex',
     u'Open Network Install Environment', u'Author Name',
     'howto', False),
]

# latex_logo
#If given, this must be the name of an image file (relative to the
#configuration directory) that is the logo of the docs. It is placed
#at the top of the title page. Default: None.

# latex_use_parts
#If true, the topmost sectioning unit is parts, else it is
#chapters. Default: False.

# latex_appendices
# A list of document names to append as an appendix to all manuals.

# latex_domain_indices
#If true, generate domain-specific indices in addition to the general
#index. For e.g. the Python domain, this is the global module
#index. Default is True.
#
#This value can be a bool or a list of index names that should be
#generated, like for html_domain_indices.

# latex_show_pagerefs
#If true, add page references after internal references. This is very
#useful for printed copies of the manual. Default is False.

# latex_show_urls

#Control whether to display URL addresses. This is very useful for
#printed copies of the manual. The setting can have the following
#values:
#
#  'no' – do not display URLs (default)
#  'footnote' – display URLs in footnotes
#  'inline' – display URLs inline in parentheses
#
# Changed in version 1.1: This value is now a string; previously it
# was a boolean value, and a true value selected the 'inline'
# display. For backwards compatibility, True is still accepted.

# latex_elements
#New in version 0.5.
#
#A dictionary that contains LaTeX snippets that override those Sphinx
#usually puts into the generated .tex files.
#
#Keep in mind that backslashes must be doubled in Python string
#literals to avoid interpretation as escape sequences.
#
#Keys that you may want to override include:
#
#'papersize'
#Paper size option of the document class ('a4paper' or 'letterpaper'),
#default 'letterpaper'.
#
#'pointsize'
#Point size option of the document class ('10pt', '11pt' or '12pt'),
#default '10pt'.
#
#'babel'
#“babel” package inclusion, default '\\usepackage{babel}'.
#
#'fontpkg'
#Font package inclusion, default '\\usepackage{times}' (which uses
#Times and Helvetica). You can set this to '' to use the Computer
#Modern fonts.
#
#'fncychap'
#Inclusion of the “fncychap” package (which makes fancy chapter
#titles), default '\\usepackage[Bjarne]{fncychap}' for English
#documentation, '\\usepackage[Sonny]{fncychap}' for internationalized
#docs (because the “Bjarne” style uses numbers spelled out in
#English). Other “fncychap” styles you can try include “Lenny”,
#“Glenn”, “Conny” and “Rejne”. You can also set this to '' to disable
#fncychap.
#
#'preamble'
#Additional preamble content, default empty.
#
#'footer'`
#Additional footer content (before the indices), default empty.
#
#Keys that don’t need be overridden unless in special cases are:
#
#'inputenc'
#“inputenc” package inclusion, default '\\usepackage[utf8]{inputenc}'.
#
#'fontenc'
#“fontenc” package inclusion, default '\\usepackage[T1]{fontenc}'.
#
#'maketitle'
#“maketitle” call, default '\\maketitle'. Override if you want to
#generate a differently-styled title page.
#
#'tableofcontents'
#“tableofcontents” call, default '\\tableofcontents'. Override if you
#want to generate a different table of contents or put content between
#the title page and the TOC.
#
#'printindex'
#“printindex” call, the last thing in the file, default
#'\\printindex'. Override if you want to generate the index
#differently or append some content after the index.
#
#Keys that are set by other options and therefore should not be
#overridden are:
#
#  'docclass' 'classoptions' 'title' 'date' 'release' 'author' 'logo'
#  'releasename' 'makeindex' 'shorthandoff'

# latex_docclass
#A dictionary mapping 'howto' and 'manual' to names of real document
#classes that will be used as the base for the two Sphinx
#classes. Default is to use 'article' for 'howto' and 'report' for
#'manual'.

# latex_additional_files
#A list of file names, relative to the configuration directory, to
#copy to the build directory when building LaTeX output. This is
#useful to copy files that Sphinx doesn’t copy automatically, e.g. if
#they are referenced in custom LaTeX added in latex_elements. Image
#files that are referenced in source files (e.g. via .. image::) are
#copied automatically.
#
#You have to make sure yourself that the filenames don’t collide with
#those of any automatically copied files.
