############################################################
# <bsn.cl fy=2013 v=none>
# 
#        Copyright 2013, 2014 BigSwitch Networks, Inc.        
# 
# 
# 
# </bsn.cl>
############################################################
ARCH=all
PACKAGE_NAMES=vendor-config-accton
include ../../../../../make/debuild.mk
