############################################################
# <bsn.cl fy=2013 v=none>
# 
#        Copyright 2013, 2014 BigSwitch Networks, Inc.        
# 
# 
# 
# </bsn.cl>
############################################################
ifndef ONL
$(error $$ONL is undefined.)
endif

# Fill me out if necessary
ONL_REQUIRED_SUBMODULES := broadcom
ONL_REQUIRED_PACKAGES := vendor-config-wnc:all

include $(ONL)/make/component.mk
