############################################################
# <bsn.cl fy=2013 v=none>
#
#        Copyright 2013, 2014 BigSwitch Networks, Inc.
#
#
#
# </bsn.cl>
############################################################
ARCH=all
PACKAGE_NAMES=platform-config-x86-64-accton-as6712-32x-r0
include ../../../../../make/debuild.mk
